import { Page, Text } from '@geist-ui/react'
import { Home as HomeIcon, Info } from '@geist-ui/icons'
import Head from 'next/head'
import React from 'react'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

/**
 * Shared layout component to wrap the entire web app. Provides the header and footer.
 * https://nextjs.org/docs/basic-features/layouts
 * @param {React.ReactNode} children node to be rendered inside this Layout Wrapper
 * @returns
 */
export default function Layout({ children }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Creativity support tool</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Page>
          <Page.Header>
            <div className={styles.headerContent}>
              <div className={styles.headerIcons}>
                <Link href="/">
                  <HomeIcon size={36} className={styles.geistHeaderIcon} />
                </Link>
                <Link href="/information">
                  <Info size={36} className={styles.geistHeaderIcon} />
                </Link>
              </div>
              <Text h1 className={styles.headerText}>
                Creativity Support Tool
              </Text>
            </div>
          </Page.Header>
          <Page.Content className={styles.pageContent}>{children}</Page.Content>
        </Page>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://epfl.ch"
          target="_blank"
          rel="noopener noreferrer"
        >
          Humboldt University of Berlin & Swiss Federal Institute of Technology
          Lausanne
        </a>
      </footer>
    </div>
  )
}
